### ISSUE TITLE
최초 설치 시 PHP 내장개발서버 작동하지 않는 문제

### ISSUE THREAD

**Issue by yuptogun** [umuusf/shakeFlat#1]
## 재현 절차

```shell
git clone git@github.com:umuusf/shakeFlat.git
cd shakeFlat/
php -S localhost:7654 -t ./htdocs
```

이상을 수행한 직후 웹브라우저로 http://localhost:7654 접속한다.

## 기대 결과

`modules/welcome/main.php` 실행에 의해 `templates/default/welcome/main.html` 기반 `text/html` 응답이 정상 표출된다.

## 실제 결과

다음 에러가 렌더링된다.

> shakeFlat Template :: default
> error message : [SYSTEM ERROR] The storage folder does not exist in the file system : E:\_others\shakeFlat\shakeFlat\storage/

## 비고: 소견

전형적인 out of the box 문제라고 생각됩니다. (포장을 열자마자 전원을 넣었는데 오작동하는 문제)
정말 필요한 디렉토리라면 적당한 `.gitignore` 파일을 하나 넣어서 커밋해 두거나, 애플리케이션이 조건부로 알아서 생성하고 관리해야 할 것입니다.

**Comment by umuusf** [comment]
테스트 및 의견 주신점 감사합니다. 
살펴보니 storage 폴더가 커밋 되지 않았습니다.
하지만 storage 폴더가 커밋되어 있더라도 몇가지 잠재적 위험요소가 있었을거 같습니다.
더불어 github에 올린 후 설치 테스트를 하지 않은 점 사과 드립니다.
