### ISSUE TITLE
실제 DB 커넥션을 사용하지 않는 라우트가 MySQL 커넥션을 시도하는 문제

### ISSUE THREAD

**Issue by yuptogun** [umuusf/shakeFlat#2]
## 재현 절차

1. 초기 설치 그대로 앱을 실행한다.
   * `config/config.ini`를 수정하지 **않음**
2. DB 데이터를 읽거나 쓰지 **않는** 라우트에 접속한다.
   * 대표적으로 `GET /welcome/main`

## 기대 결과

해당 라우트의 처리가 정상적으로 완수된다.

## 실제 결과

다음 오류가 렌더링된다.

> shakeFlat Template :: default
> error message : SQLSTATE[HY000] [1045] Access denied for user 'shakeflat'@'localhost' (using password: YES) (1045)

## 비고: 소견

또다른 out of the box 문제입니다. DB에 접근할 필요가 없는 요청을 보내는데도 `setTransaction()`이 항상 수행되고 있어서 발생하는 현상으로 보입니다. shakeFlat을 사용하기 위해 반드시 DB가 필요한 것이 아니라면, 이 문제는 해결되어야 할 것 같습니다.

**Comment by umuusf** [comment]
포함된 index.php 는 프레임웍 패키지라기 보다는 예제 소스에 가깝습니다.
메뉴얼 작성이 되지 않은 상태이기 때문에 index.php 외에도 몇가지 예제 소스를 첨부하여 실행 방식의 이해를 돕고자 하였습니다.
하지만 말씀하신데로 초기 설치시 바로 실행되지 않는 부분은 수정이 필요해 보입니다.
