### ISSUE TITLE
프레임워크 소스 확장자는 반드시 .inc여야 하는지?

### ISSUE THREAD

**Issue by yuptogun** [umuusf/shakeFlat#3]
파일 확장자가 `.inc`라는 이유만으로 (VS Code 등의 IDE 사용시) 불필요한 불편이 발생하고 있습니다.

* PHP 포맷으로 하이라이트를 해주지 않음
* 인덱싱/정적분석 등이 정상 수행되지 않음

본 확장자는 (별다른 규칙이랄 게 없던) PHP 4 시절의 관행을 따르는 것으로 보이는데, 이를 `.php`로 변경할 수 없는 이유가 있나요?

**Comment by umuusf** [comment]
말씀 하신데로 오래된 관행일 뿐이고, 저는 그것이 편하기 때문에 그렇게 사용합니다.
저는 VSCode 에서 inc 확장자를 등록해서 사용 중 이며 불편을 느끼지 못하고 있습니다.

**Comment by yuptogun** [comment]
아~ 네 프레임워크 개성이라고 이해하겠습니다.
