### ISSUE TITLE
위계질서의 문제: App 클래스가 로깅클래스를 상속하는 것이 타당한지?

### ISSUE THREAD

**Issue by yuptogun** [umuusf/shakeFlat#4]
`core/core.inc`를 열어보면 다음과 같이 되어 있습니다.

```php
use shakeFlat\libs\L;
class App extends L { ... }
```

그리고 찾아보면, `shakeFlat\libs\L`은 원칙적으로는, 로깅을 하는 클래스입니다.
이렇게만 놓고 보면, `shakeFlat\App`은, **HTTP 요청을 처리할 수 있는 (그리고 그 임무를 단독 수행하는) 로깅 클래스**입니다.

## 질문

1. 이것은 타당한 구조/위계인가요? 만약 그렇다면 왜인가요?
2. 이것이 타당한 구조/위계가 아니라면, 예컨대 `shakeFlat\App` 클래스 및 일부 메소드를 다음과 같이 고친다면 어떨까요?

```php
class App // L을 확장하지 않는다.
{
  private function exit(string $message = 'Something went wrong.'): void
  {
    // L 클래스를 가져와서는 로그만 시키고, 실제 php 스크립트 종료는 App이 한다.
    // L 클래스의 _terminate 안에 있는 exit는 삭제한다.
    $logger = new shakeFlat\libs\L;
    $logger::_terminate($message);
    exit;
  }
}
```

**Comment by umuusf** [comment]
L 클래스는 코딩의 편의를 위해 static method 호출을 하거나 혹은 부모 클래스로서 사용하기 위해서 설계된 클래스입니다.
그에 비해 Log 클래스는 독립된 클래스로 설계되었습니다.
로깅은 모든 코드에서 사용되기 때문에 일부러 Log클래스외에 L클래스를 별도로 구성한 것입니다.
